### ISSUE TITLE
请问actions出错，卡在这是怎么回事

### ISSUE THREAD

**Issue by huairen306** [QiuYueBaiJXW/UnicomGetCoin#4]
build
failed 12 minutes ago in 7s
Search logs
2s
1s
2s
1s
Run python3 UnicomAutoGetCoin.py ${cookie}
Traceback (most recent call last):
  File "UnicomAutoGetCoin.py", line 81, in <module>
    user.sign(data)
  File "UnicomAutoGetCoin.py", line 40, in sign
    req2 = urllib2.urlopen(req2,data)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
Error: Process completed with exit code 1.

**Comment by ye1314** [comment]
我搞出来了，复制开头simCount到结束
